print("Hello GitHub!")
name = input("What is your name? ")
print("Hello", name)
print("This line was added from VS Code!")
print("This line was added from GitHub!")
print("This line was pushed from Git Bash!")
print("This line was added from GitHub for VS Code pull!")
